;;; beacon-preview.el --- Minimal xwidget proof of concept -*- lexical-binding: t; -*-

;; Author: Codex prototype
;; Keywords: hypermedia, tools
;; Package-Requires: ((emacs "29.1"))

;;; Commentary:

;; This is a thin proof of concept for driving beaconable HTML generated by the
;; prototype post-processor in this repository.
;;
;; Expected workflow:
;;
;; 1. Generate HTML with scripts/beaconify_html.py --inject-navigation-api
;; 2. Open that HTML in an xwidget webkit buffer
;; 3. Jump to block-level anchors by calling window.BeaconPreview from Emacs
;; 4. For Markdown headings, derive a Pandoc-like anchor from the source line

;;; Code:

(require 'subr-x)
(require 'json)
(require 'url-util)

(defgroup beacon-preview nil
  "Preview local beaconable HTML in xwidget."
  :group 'tools
  :prefix "beacon-preview-")

(defun beacon-preview--library-directory ()
  "Return the directory containing beacon-preview.el, or nil."
  (let ((library-file (or load-file-name
                          (ignore-errors
                            (find-library-name "beacon-preview")))))
    (when library-file
      (file-name-directory (expand-file-name library-file)))))

(defun beacon-preview--default-builder-script ()
  "Return the default path to build_preview.py."
  (if-let ((library-dir (beacon-preview--library-directory)))
      (expand-file-name "../scripts/build_preview.py" library-dir)
    "build_preview.py"))

(defcustom beacon-preview-open-function #'xwidget-webkit-browse-url
  "Function used to open a generated preview URL in a new xwidget session."
  :type 'function)

(defcustom beacon-preview-python-command "python3"
  "Python executable used to run the preview builder script."
  :type 'string)

(defcustom beacon-preview-pandoc-command "pandoc"
  "Pandoc executable used by the preview builder script."
  :type 'string)

(defcustom beacon-preview-builder-script
  (beacon-preview--default-builder-script)
  "Path to the build_preview.py script."
  :type 'file)

(defcustom beacon-preview-display-buffer-action
  '((display-buffer-reuse-window display-buffer-in-side-window)
    (side . right)
    (slot . 0)
    (window-width . 0.5)
    (inhibit-same-window . t))
  "Display action used for xwidget preview buffers.

The default reuses an existing preview window when possible and otherwise
opens the preview in a right side window without replacing the editing buffer."
  :type 'sexp)

(defcustom beacon-preview-temporary-root
  (expand-file-name "beacon-preview/" temporary-file-directory)
  "Root directory for internally managed temporary preview artifacts."
  :type 'directory)

(defcustom beacon-preview-source-modes '(markdown-mode gfm-mode)
  "Major modes where source-side heading helpers should be offered."
  :type '(repeat symbol))

(defcustom beacon-preview-auto-refresh-on-save t
  "Whether `beacon-preview-mode' should refresh preview artifacts on save."
  :type 'boolean)

(defcustom beacon-preview-follow-current-heading-on-refresh t
  "Whether refresh commands should reopen the preview at the current heading."
  :type 'boolean)

(defcustom beacon-preview-follow-window-position t
  "Whether preview jumps should roughly match point's vertical position in the source window."
  :type 'boolean)

(defcustom beacon-preview-post-open-sync-delay 0.05
  "Delay in seconds before applying a post-open preview position sync."
  :type 'number)

(defcustom beacon-preview-jump-retry-count 20
  "How many times the browser-side jump script should retry before giving up."
  :type 'integer)

(defcustom beacon-preview-jump-retry-delay-ms 50
  "Delay in milliseconds between browser-side jump retries."
  :type 'integer)

(defcustom beacon-preview-debug nil
  "Whether beacon preview should emit debug messages to `*Messages*'."
  :type 'boolean)

(defvar beacon-preview--last-url nil
  "Last URL opened by beacon preview.")

(defvar beacon-preview--last-html-path nil
  "Path to the last generated preview HTML file.")

(defvar beacon-preview--manifest nil
  "Cached beacon manifest loaded from JSON.")

(defvar beacon-preview--manifest-path nil
  "Path of the currently loaded beacon manifest.")

(defvar-local beacon-preview--xwidget-buffer nil
  "Buffer showing the beacon preview via xwidget for the current source buffer.")

(defvar-local beacon-preview--source-buffer nil
  "Source buffer associated with a preview buffer.")

(defvar-local beacon-preview--pending-sync-script nil
  "Pending JavaScript to run after the current preview load finishes.")

(defvar-local beacon-preview--pending-sync-generation 0
  "Monotonic generation number for queued preview sync requests.")

(defvar-local beacon-preview--pending-sync-timer nil
  "Timer scheduled to execute the latest queued preview sync.")

(defvar beacon-preview-command-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "o") #'beacon-preview-build-and-open)
    (define-key map (kbd "r") #'beacon-preview-build-and-refresh)
    (define-key map (kbd "j") #'beacon-preview-jump-to-current-heading)
    (define-key map (kbd "a") #'beacon-preview-jump-to-anchor)
    (define-key map (kbd "d") #'beacon-preview-toggle-debug)
    map)
  "Prefix keymap for `beacon-preview-mode' commands.")

(defvar beacon-preview-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-b") beacon-preview-command-map)
    map)
  "Keymap for `beacon-preview-mode'.")

(defun beacon-preview--debug (format-string &rest args)
  "Emit a beacon preview debug message using FORMAT-STRING and ARGS."
  (when beacon-preview-debug
    (apply #'message (concat "[beacon-preview] " format-string) args)))

(defun beacon-preview-toggle-debug (&optional arg)
  "Toggle beacon preview debug logging.

With prefix ARG, enable debug logging when ARG is positive, otherwise disable
it."
  (interactive "P")
  (setq beacon-preview-debug
        (if arg
            (> (prefix-numeric-value arg) 0)
          (not beacon-preview-debug)))
  (message "[beacon-preview] debug %s"
           (if beacon-preview-debug "enabled" "disabled")))

(defun beacon-preview--supported-source-mode-p ()
  "Return non-nil when the current buffer is supported for source-side features."
  (apply #'derived-mode-p beacon-preview-source-modes))

(defun beacon-preview--ensure-xwidget-loaded ()
  "Load xwidget support if available, returning non-nil on success."
  (or (featurep 'xwidget)
      (require 'xwidget nil t)))

(defun beacon-preview--xwidget-available-p ()
  "Return non-nil when xwidget webkit preview is available."
  (and (beacon-preview--ensure-xwidget-loaded)
       (display-graphic-p)
       (featurep 'xwidget-internal)
       (fboundp 'xwidget-webkit-browse-url)
       (fboundp 'xwidget-webkit-current-session)
       (fboundp 'xwidget-webkit-goto-url)))

(defun beacon-preview--xwidget-session ()
  "Return the xwidget session for the current source buffer's preview."
  (when (buffer-live-p beacon-preview--xwidget-buffer)
    (with-current-buffer beacon-preview--xwidget-buffer
      (xwidget-webkit-current-session))))

(defun beacon-preview--live-preview-p ()
  "Return non-nil when the current source buffer has a live preview session."
  (and (buffer-live-p beacon-preview--xwidget-buffer)
       (beacon-preview--xwidget-session)))

(defun beacon-preview--file-url (file)
  "Return a file:// URL for FILE."
  (concat "file://" (expand-file-name file)))

(defun beacon-preview--current-heading-anchor-maybe ()
  "Return the current heading anchor when source-side lookup is applicable."
  (when (and beacon-preview-follow-current-heading-on-refresh
             (beacon-preview--supported-source-mode-p))
    (ignore-errors
      (beacon-preview-current-heading-anchor))))

(defun beacon-preview--preview-url (file &optional anchor)
  "Return a preview URL for FILE, optionally targeting ANCHOR."
  (concat (beacon-preview--file-url file)
          (if (and anchor (not (string-empty-p anchor)))
              (concat "#" (url-hexify-string anchor))
            "")))

(defun beacon-preview--xwidget-callback (xwidget event-type)
  "Handle XWIDGET EVENT-TYPE and run pending preview sync after load finishes."
  (xwidget-webkit-callback xwidget event-type)
  (beacon-preview--debug "xwidget callback event=%S detail=%S"
                         event-type
                         (nth 3 last-input-event))
  (when (and (eq event-type 'load-changed)
             (string-equal (nth 3 last-input-event) "load-finished"))
    (with-current-buffer (xwidget-buffer xwidget)
      (when beacon-preview--pending-sync-script
        (let ((script beacon-preview--pending-sync-script)
              (generation beacon-preview--pending-sync-generation))
          (beacon-preview--debug "load finished; running pending sync")
          (setq beacon-preview--pending-sync-script nil)
          (when (timerp beacon-preview--pending-sync-timer)
            (cancel-timer beacon-preview--pending-sync-timer))
          (setq beacon-preview--pending-sync-timer
                (run-at-time
                 beacon-preview-post-open-sync-delay
                 nil
                 (lambda ()
                   (when (buffer-live-p (xwidget-buffer xwidget))
                     (with-current-buffer (xwidget-buffer xwidget)
                       (when (= generation beacon-preview--pending-sync-generation)
                         (setq beacon-preview--pending-sync-timer nil)
                         (beacon-preview--debug
                          "executing pending sync script generation=%d"
                          generation)
                         (xwidget-webkit-execute-script
                          xwidget
                          script))))))))))))

(defun beacon-preview--install-xwidget-callback (preview-buffer)
  "Install the beacon preview xwidget callback into PREVIEW-BUFFER."
  (when (buffer-live-p preview-buffer)
    (with-current-buffer preview-buffer
      (when-let ((session (and (fboundp 'xwidget-webkit-current-session)
                               (xwidget-webkit-current-session))))
        (xwidget-put session 'callback #'beacon-preview--xwidget-callback)))))

(defun beacon-preview--queue-position-sync (preview-buffer anchor ratio)
  "Queue a post-load sync for PREVIEW-BUFFER to ANCHOR at RATIO."
  (when (and (buffer-live-p preview-buffer)
             anchor
             ratio)
    (with-current-buffer preview-buffer
      (setq beacon-preview--pending-sync-generation
            (1+ beacon-preview--pending-sync-generation))
      (beacon-preview--debug "queue sync anchor=%S ratio=%.4f buffer=%s"
                             anchor ratio (buffer-name preview-buffer))
      (setq beacon-preview--pending-sync-script
            (beacon-preview--jump-script anchor ratio)))))

(defun beacon-preview--source-window (&optional buffer)
  "Return a live window displaying BUFFER, preferring the selected window."
  (let ((buffer (or buffer (current-buffer))))
    (cond
     ((eq (window-buffer (selected-window)) buffer)
      (selected-window))
     (t
      (get-buffer-window buffer t)))))

(defun beacon-preview--window-line-ratio (&optional window position)
  "Return POSITION's approximate vertical ratio within WINDOW.

The value is clamped to the `[0.0, 1.0]' range."
  (let* ((window (or window (selected-window)))
         (start (window-start window))
         (position (or position (point)))
         (window-lines (max 1 (window-body-height window t)))
         (visible-index
          (max 0
               (1- (count-screen-lines start position nil window)))))
    (min 1.0
         (max 0.0
              (/ (float visible-index)
                 (float window-lines))))))

(defun beacon-preview--window-pixel-y-for-pos (&optional window position)
  "Return POSITION's Y pixel coordinate within WINDOW, or nil."
  (let* ((window (or window (selected-window)))
         (position (or position (point)))
         (posn (posn-at-point position window))
         (xy (and posn (posn-x-y posn))))
    (when xy
      (cdr xy))))

(defun beacon-preview--window-visible-ratio-for-pos (&optional window position)
  "Return POSITION's vertical ratio within WINDOW if it is currently visible.

Return nil when POSITION is not visible in WINDOW."
  (let* ((window (or window (selected-window)))
         (position (or position (point)))
         (visible (pos-visible-in-window-p position window)))
    (beacon-preview--debug
     "visible-ratio pos=%S window-start=%S visible=%S"
     position
     (window-start window)
     visible)
    (when visible
      (let* ((y (beacon-preview--window-pixel-y-for-pos window position))
             (body-pixels (window-body-height window t))
             (ratio (if (and y (> body-pixels 0))
                        (/ (float y) (float body-pixels))
                      (beacon-preview--window-line-ratio window position))))
        (beacon-preview--debug "visible-ratio result=%.4f" ratio)
        ratio))))

(defun beacon-preview--effective-window-ratio (ratio)
  "Convert source window RATIO into a gentler preview offset ratio.

This keeps lower cursor positions from pushing the preview target too far down
the viewport."
  (/ ratio (+ 1.0 ratio)))

(defun beacon-preview--target-source-position-maybe ()
  "Return the source position for the current jump target, or nil.

The current implementation uses the selected heading position, but this helper
is intentionally generic so future block anchors can reuse the same offset
pipeline."
  (when-let ((heading (beacon-preview--markdown-current-heading-info)))
    (plist-get heading :pos)))

(defun beacon-preview--jump-script (anchor &optional ratio)
  "Return JavaScript to jump to ANCHOR, offset by RATIO of the viewport height."
  (format
   (concat "(function () {"
           "  var anchor = %S;"
           "  var ratio = %s;"
           "  var retries = %d;"
           "  var retryDelay = %d;"
           "  function jump() {"
           "    var element = document.getElementById(anchor);"
           "    if (!element) {"
           "      if (retries > 0) {"
           "        retries -= 1;"
           "        window.setTimeout(jump, retryDelay);"
           "      }"
           "      return false;"
           "    }"
           "    var rect = element.getBoundingClientRect();"
           "    var targetY = rect.top + window.scrollY - (window.innerHeight * ratio);"
           "    window.scrollTo(0, Math.max(0, targetY));"
           "    return true;"
           "  }"
           "  return jump();"
           "})();")
   anchor
   (if ratio
       (format "%.10f" ratio)
     "0.0")
   beacon-preview-jump-retry-count
   beacon-preview-jump-retry-delay-ms))

(defun beacon-preview--preview-buffer-name (&optional source-buffer)
  "Return the desired preview buffer name for SOURCE-BUFFER."
  (let* ((buffer (or source-buffer (current-buffer)))
         (file (buffer-file-name buffer))
         (label (if file
                    (file-name-nondirectory file)
                  (buffer-name buffer))))
    (format "*beacon-preview: %s*" label)))

(defun beacon-preview--label-preview-buffer (preview-buffer source-buffer)
  "Associate PREVIEW-BUFFER with SOURCE-BUFFER and rename it for clarity."
  (when (buffer-live-p preview-buffer)
    (with-current-buffer preview-buffer
      (setq beacon-preview--source-buffer source-buffer)
      (beacon-preview--install-xwidget-callback preview-buffer)
      (rename-buffer (beacon-preview--preview-buffer-name source-buffer) t))))

(defun beacon-preview--show-preview-buffer (preview-buffer)
  "Display PREVIEW-BUFFER in a user-visible window."
  (display-buffer preview-buffer beacon-preview-display-buffer-action))

(defun beacon-preview--artifact-base-name (file)
  "Return the artifact base name derived from FILE."
  (file-name-base (expand-file-name file)))

(defun beacon-preview--source-temp-directory (source-file)
  "Return the internal temporary directory for SOURCE-FILE."
  (let* ((source-path (expand-file-name source-file))
         (source-hash (secure-hash 'sha1 source-path))
         (base-name (beacon-preview--artifact-base-name source-file))
         (root (file-name-as-directory
                (expand-file-name beacon-preview-temporary-root))))
    (expand-file-name (format "%s-%s" base-name (substring source-hash 0 12))
                      root)))

(defun beacon-preview--artifact-paths (source-file)
  "Return plist of output artifact paths for SOURCE-FILE."
  (let* ((base (beacon-preview--artifact-base-name source-file))
         (output-dir (beacon-preview--source-temp-directory source-file)))
    (list :html (expand-file-name (format "%s.html" base) output-dir)
          :manifest (expand-file-name (format "%s.json" base) output-dir))))

(defun beacon-preview--source-file ()
  "Return the current buffer file or signal an error."
  (or (buffer-file-name)
      (user-error "Current buffer is not visiting a file")))

(defun beacon-preview--open-preview (file &optional anchor)
  "Open FILE as a beacon preview in xwidget, optionally targeting ANCHOR."
  (unless (beacon-preview--xwidget-available-p)
    (user-error
     (concat
      "xwidget-webkit preview is unavailable; "
      "this Emacs must be built with xwidgets and running in a graphical session")))
  (let* ((source-buffer (current-buffer))
         (source-window (beacon-preview--source-window source-buffer))
         (target-source-position (beacon-preview--target-source-position-maybe))
         (raw-ratio (and anchor
                         source-window
                         target-source-position
                         beacon-preview-follow-window-position
                         (beacon-preview--window-visible-ratio-for-pos
                          source-window
                          target-source-position)))
         (ratio (and raw-ratio
                     (beacon-preview--effective-window-ratio raw-ratio)))
         (url (if ratio
                  (beacon-preview--file-url file)
                (beacon-preview--preview-url file anchor))))
    (beacon-preview--debug
     "open-preview anchor=%S target-pos=%S raw-ratio=%S ratio=%S url=%s"
     anchor target-source-position raw-ratio ratio url)
    (setq beacon-preview--last-url url)
    (setq beacon-preview--last-html-path (expand-file-name file))
    (let ((window (beacon-preview--show-preview-buffer
                   (or beacon-preview--xwidget-buffer source-buffer))))
      (with-selected-window window
        (if (beacon-preview--live-preview-p)
            (progn
              (switch-to-buffer beacon-preview--xwidget-buffer)
              (beacon-preview--queue-position-sync
               beacon-preview--xwidget-buffer anchor ratio)
              (xwidget-webkit-goto-url url))
          (funcall beacon-preview-open-function url t)
          (when-let ((session (or (and (boundp 'xwidget-webkit-last-session)
                                       xwidget-webkit-last-session)
                                  (xwidget-webkit-current-session))))
            (with-current-buffer source-buffer
              (setq beacon-preview--xwidget-buffer
                    (xwidget-buffer session))
              (beacon-preview--label-preview-buffer
               beacon-preview--xwidget-buffer
               source-buffer)
              (beacon-preview--queue-position-sync
               beacon-preview--xwidget-buffer anchor ratio))))))))

(defun beacon-preview-load-manifest (file)
  "Load FILE as the active beacon manifest."
  (interactive "fBeacon manifest JSON: ")
  (setq beacon-preview--manifest-path (expand-file-name file))
  (setq beacon-preview--manifest
        (condition-case err
            (json-read-file beacon-preview--manifest-path)
          (error
           (user-error "Failed to load manifest %s: %s"
                       beacon-preview--manifest-path
                       (error-message-string err)))))
  beacon-preview--manifest)

(defun beacon-preview-clear-manifest ()
  "Clear the cached beacon manifest."
  (interactive)
  (setq beacon-preview--manifest nil)
  (setq beacon-preview--manifest-path nil))

(defun beacon-preview--command-available-p (command)
  "Return non-nil when COMMAND appears runnable in the current environment."
  (cond
   ((or (null command) (string-empty-p command)) nil)
   ((file-name-absolute-p command)
    (file-executable-p command))
   ((file-name-directory command)
    (file-executable-p (expand-file-name command default-directory)))
   (t
    (not (null (executable-find command))))))

(defun beacon-preview--build-error-message (output-buffer)
  "Return a concise build error message using OUTPUT-BUFFER contents."
  (with-current-buffer (get-buffer-create output-buffer)
    (goto-char (point-min))
    (let ((line (string-trim
                 (or (buffer-substring-no-properties
                      (line-beginning-position)
                      (line-end-position))
                     ""))))
      (if (string-empty-p line)
          (format "Preview build failed; see %s for details" output-buffer)
        (format "Preview build failed: %s" line)))))

(defun beacon-preview-build-current-file ()
  "Build preview artifacts for the current source file.

Returns a plist with `:html' and `:manifest' paths."
  (interactive)
  (let* ((source-file (beacon-preview--source-file))
         (default-directory (file-name-directory source-file))
         (artifacts (beacon-preview--artifact-paths source-file))
         (html-path (plist-get artifacts :html))
         (manifest-path (plist-get artifacts :manifest))
         (builder-script (expand-file-name beacon-preview-builder-script))
         (output-buffer "*beacon-preview-build*")
         (output-dir (beacon-preview--source-temp-directory source-file))
         exit-code)
    (unless (beacon-preview--command-available-p beacon-preview-python-command)
      (user-error "Python executable not found: %s" beacon-preview-python-command))
    (unless (file-exists-p builder-script)
      (user-error "Preview builder script not found: %s" builder-script))
    (unless (beacon-preview--command-available-p beacon-preview-pandoc-command)
      (user-error "Pandoc executable not found: %s" beacon-preview-pandoc-command))
    (setq exit-code
          (condition-case err
              (call-process
               beacon-preview-python-command
               nil
               output-buffer
               nil
               builder-script
               "--input"
               source-file
               "--output-dir"
               output-dir
               "--pandoc"
               beacon-preview-pandoc-command)
            (file-missing
             (user-error "Failed to start preview builder: %s"
                         (error-message-string err)))))
    (unless (and (integerp exit-code) (zerop exit-code))
      (pop-to-buffer output-buffer)
      (user-error "%s" (beacon-preview--build-error-message output-buffer)))
    (setq beacon-preview--last-html-path html-path)
    (beacon-preview-load-manifest manifest-path)
    (when (called-interactively-p 'interactive)
      (message "Built preview: %s" html-path))
    artifacts))

(defun beacon-preview--after-save ()
  "Refresh the current preview after saving the source buffer."
  (when (and beacon-preview-auto-refresh-on-save
             (beacon-preview--supported-source-mode-p)
             (buffer-file-name))
    (beacon-preview-build-and-refresh)))

(defun beacon-preview-build-and-open ()
  "Build preview artifacts for the current file and open the HTML preview."
  (interactive)
  (let* ((artifacts (beacon-preview-build-current-file))
         (html-path (plist-get artifacts :html))
         (anchor (beacon-preview--current-heading-anchor-maybe)))
    (beacon-preview--open-preview html-path anchor)))

(defun beacon-preview-build-and-refresh ()
  "Build preview artifacts, reload the manifest, and refresh the preview.

If no preview is open yet, open the generated HTML."
  (interactive)
  (let* ((artifacts (beacon-preview-build-current-file))
         (html-path (plist-get artifacts :html))
         (anchor (beacon-preview--current-heading-anchor-maybe)))
    (beacon-preview--open-preview html-path anchor)))

(defun beacon-preview-switch-to-preview ()
  "Select the current source buffer's preview buffer."
  (interactive)
  (unless (buffer-live-p beacon-preview--xwidget-buffer)
    (user-error "No live preview buffer is associated with this source buffer"))
  (beacon-preview--show-preview-buffer beacon-preview--xwidget-buffer))

(defun beacon-preview--current-session ()
  "Return the current xwidget webkit session or signal a user error."
  (or (beacon-preview--xwidget-session)
      (user-error "No active xwidget webkit session found")))

(defun beacon-preview--execute-script (script)
  "Execute JavaScript SCRIPT in the current preview session."
  (xwidget-webkit-execute-script
   (beacon-preview--current-session)
   script))

(defun beacon-preview-jump-to-anchor (anchor)
  "Jump the current preview to ANCHOR using the injected BeaconPreview API."
  (interactive "sAnchor: ")
  (let* ((source-window (beacon-preview--source-window (current-buffer)))
         (target-source-position (beacon-preview--target-source-position-maybe))
         (raw-ratio (and beacon-preview-follow-window-position
                         source-window
                         target-source-position
                         (beacon-preview--window-visible-ratio-for-pos
                          source-window
                          target-source-position)))
         (ratio (and raw-ratio
                     (beacon-preview--effective-window-ratio raw-ratio))))
    (beacon-preview--debug
     "jump-to-anchor anchor=%S target-pos=%S raw-ratio=%S ratio=%S"
     anchor target-source-position raw-ratio ratio)
    (beacon-preview--execute-script
     (beacon-preview--jump-script anchor ratio))))

(defun beacon-preview-jump-to-index (kind index)
  "Jump the current preview to beacon KIND at INDEX."
  (interactive
   (list
    (completing-read
     "Kind: "
     '("h1" "h2" "h3" "h4" "h5" "h6" "p" "li" "blockquote" "pre" "table" "div")
     nil
     t)
    (read-number "Index: " 1)))
  (beacon-preview--execute-script
   (format
    (concat "(function () {"
            " if (!window.BeaconPreview) { return false; }"
            " return window.BeaconPreview.jumpToIndex(%S, %d);"
            "})();")
    kind
    index)))

(defun beacon-preview-reload ()
  "Reload the current beacon preview."
  (interactive)
  (beacon-preview--execute-script "window.location.reload();"))

(defun beacon-preview--markdown-heading-text-at-point ()
  "Return ATX Markdown heading text at point, or nil if the line is not a heading."
  (save-excursion
    (beginning-of-line)
    (when (looking-at "^[ \t]\\{0,3\\}\\(#+\\)[ \t]+\\(.+?\\)[ \t]*#*[ \t]*$")
      (let ((level (length (match-string-no-properties 1))))
        (when (<= level 6)
          (list :level level
                :text (string-trim (match-string-no-properties 2))))))))

(defun beacon-preview--markdown-setext-heading-text-at-point ()
  "Return setext heading text at point, or nil if the current line is not a setext heading text line."
  (save-excursion
    (beginning-of-line)
    (let ((text (string-trim
                 (buffer-substring-no-properties
                  (line-beginning-position)
                  (line-end-position)))))
      (when (and (not (string-empty-p text))
                 (zerop (forward-line 1))
                 (looking-at "^[ \t]\\{0,3\\}\\(=+\\|-+\\)[ \t]*$"))
        (list :level (if (eq (char-after (match-beginning 1)) ?=) 1 2)
              :text text)))))

(defun beacon-preview--markdown-setext-heading-at-point ()
  "Return setext heading plist at point, or nil if not on a setext underline."
  (save-excursion
    (beginning-of-line)
    (when (looking-at "^[ \t]\\{0,3\\}\\(=+\\|-+\\)[ \t]*$")
      (let ((level (if (eq (char-after (match-beginning 1)) ?=) 1 2)))
        (when (zerop (forward-line -1))
          (let ((text (string-trim
                       (buffer-substring-no-properties
                        (line-beginning-position)
                        (line-end-position)))))
            (unless (string-empty-p text)
              (list :level level :text text))))))))

(defun beacon-preview--markdown-heading-at-point ()
  "Return a Markdown heading plist at point, or nil."
  (or (beacon-preview--markdown-heading-text-at-point)
      (beacon-preview--markdown-setext-heading-at-point)))

(defun beacon-preview--markdown-heading-info-at-point ()
  "Return a Markdown heading plist at point, including its source position."
  (when-let ((heading (beacon-preview--markdown-heading-at-point)))
    (append heading (list :pos (line-beginning-position)))))

(defun beacon-preview--markdown-setext-heading-info-at-point ()
  "Return setext heading text at point or above, including source position."
  (save-excursion
    (beginning-of-line)
    (when-let ((heading (beacon-preview--markdown-setext-heading-text-at-point)))
      (forward-line -1)
      (append heading (list :pos (line-beginning-position))))))

(defun beacon-preview--markdown-current-heading-info ()
  "Return the nearest Markdown heading at or before point, including `:pos'."
  (save-excursion
    (catch 'heading
      (or (beacon-preview--markdown-heading-info-at-point)
          (beacon-preview--markdown-setext-heading-info-at-point)
          (progn
            (beginning-of-line)
            (while (not (bobp))
              (forward-line -1)
              (when-let ((heading (or (beacon-preview--markdown-heading-info-at-point)
                                      (beacon-preview--markdown-setext-heading-info-at-point))))
                (throw 'heading heading)))
            nil)))))

(defun beacon-preview--markdown-current-heading ()
  "Return the nearest Markdown heading text at or before point.

The search is intentionally small and predictable for the prototype."
  (when-let ((heading (beacon-preview--markdown-current-heading-info)))
    (list :level (plist-get heading :level)
          :text (plist-get heading :text))))

(defun beacon-preview--markdown-heading-occurrence (heading)
  "Return 1-based occurrence count for HEADING up to point.

HEADING is a plist with :level and :text."
  (save-excursion
    (let ((count 0)
          (target-level (plist-get heading :level))
          (target-text (plist-get heading :text))
          (limit (point)))
      (save-restriction
        (narrow-to-region (point-min) limit)
        (goto-char (point-min))
        (while (not (eobp))
          (when-let ((candidate (or (beacon-preview--markdown-heading-text-at-point)
                                    (beacon-preview--markdown-setext-heading-text-at-point))))
            (when (and (= (plist-get candidate :level) target-level)
                       (string= (plist-get candidate :text) target-text))
              (setq count (1+ count))))
          (forward-line 1)))
      count)))

(defun beacon-preview--pandoc-like-slug (text)
  "Convert TEXT into a simple Pandoc-like heading anchor.

This aims to be closer to Pandoc's generated heading identifiers."
  (let ((result nil)
        (pending-hyphen nil))
    (dolist (char (string-to-list (downcase (string-trim text))))
      (cond
       ((eq char ?-)
        (when result
          (push ?- result))
        (setq pending-hyphen nil))
       ((memq (char-syntax char) '(?\  ))
        (setq pending-hyphen (not (null result))))
       ((or (eq char ?_)
            (memq (get-char-code-property char 'general-category)
                  '(Ll Lm Lo Lt Lu Nd Nl No Mc Me Mn Pc)))
        (when pending-hyphen
          (push ?- result)
          (setq pending-hyphen nil))
        (push char result))
       (t nil)))
    (setq result (nreverse result))
    (string-trim (concat result) "-+" "-+")))

(defun beacon-preview-current-heading-anchor ()
  "Return the preview anchor for the current Markdown heading context."
  (interactive)
  (unless (beacon-preview--supported-source-mode-p)
    (user-error "Current mode is not configured for source-side beacon lookup"))
  (let ((heading (beacon-preview--markdown-current-heading)))
    (unless heading
      (user-error "No Markdown heading found at or before point"))
    (let* ((resolved (beacon-preview--resolve-heading-anchor heading))
           (occurrence (beacon-preview--markdown-heading-occurrence heading))
           (base-anchor (beacon-preview--pandoc-like-slug
                         (plist-get heading :text)))
           (anchor (or resolved
                       (if (> occurrence 1)
                           (format "%s-%d" base-anchor (1- occurrence))
                         base-anchor))))
      (when (called-interactively-p 'interactive)
        (message "%s" anchor))
      anchor)))

(defun beacon-preview--manifest-entries ()
  "Return cached manifest entries as a plain list."
  (and beacon-preview--manifest
       (append beacon-preview--manifest nil)))

(defun beacon-preview--resolve-heading-anchor (heading)
  "Resolve HEADING through the loaded manifest if possible."
  (let* ((kind (format "h%d" (plist-get heading :level)))
         (text (plist-get heading :text))
         (occurrence (beacon-preview--markdown-heading-occurrence heading))
         (matches nil))
    (dolist (entry (beacon-preview--manifest-entries))
      (when (and (equal (alist-get 'kind entry) kind)
                 (equal (alist-get 'text entry) text))
        (push entry matches)))
    (setq matches (nreverse matches))
    (alist-get 'anchor (nth (1- occurrence) matches))))

(defun beacon-preview-jump-to-current-heading ()
  "Jump preview to the anchor derived from the current Markdown heading."
  (interactive)
  (beacon-preview-jump-to-anchor
   (beacon-preview-current-heading-anchor)))

(define-minor-mode beacon-preview-mode
  "Minor mode for beacon preview integration in source buffers."
  :lighter " Beacon"
  :keymap beacon-preview-mode-map
  (if beacon-preview-mode
      (add-hook 'after-save-hook #'beacon-preview--after-save nil t)
    (remove-hook 'after-save-hook #'beacon-preview--after-save t)))

(provide 'beacon-preview)

;;; beacon-preview.el ends here
